### ISSUE TITLE
Balance Sheet not show Retained Earnings 

### ISSUE THREAD

**Issue by DarithSoy** [bigcapitalhq/bigcapital#265]
Balance Sheet is unequal between Asset = Liabilities + Equities because the number forward from Net Income does not show on Retained Earning.

**Comment by abouolia** [comment]
The retained earning and net income are different things, when we designed the report, we did it in traditional way, not showing net income row in the balance sheet, the assets and liability get balanced after closing expenses and income account.

You can see retained earning account under equity section (if it has balance of course) because the root type of the account is equity EOD.

But after deep thinking about this and communication with the team, it would be better to add "Net Income" as computed row (not as normal account) to adjust the equity section then liability and assets will be equal.

**Comment by abouolia** [comment]
I've created a task for this https://linear.app/bigcaptial/issue/BIG-77/computed-net-income-under-equity-in-balance-sheet-report

**Comment by DarithSoy** [comment]
The Retained Earnings under the equities account (Increase/Decrease) and the retained earnings are calculated based on results from the net income accumulated amount as of the period.
For example: 
Net Income: Jan-23 = -400, Feb-23 = 500, Mar-23 = 200;
If we run the Balance Sheet as at:
     Feb-23: is 100 (Jan-23 + Feb-23)
     Mar-23: is 300 (Jan-23 + Feb-23+ Mar-23)

**Comment by abouolia** [comment]
The problem has been fixed https://github.com/bigcapitalhq/bigcapital/pull/271, thanks a lot for mentioning that.
