### ISSUE TITLE
ARM support (Raspbian / Raspberry Pi) + feedback

### ISSUE THREAD

**Issue by robertalexa** [bigcapitalhq/bigcapital#296]
Hi @abouolia 

Firstly, thanks for the efforts in creating this open source project. I have found references to it on reddit r/selfhosted and decided to give it a try.

By the looks of it, the docker setup is not supported on arm architecture?

```
 > [REDACTED_database_migration 2/7] RUN apk update &&   apk upgrade &&   apk add git:
#16 0.654 exec /bin/sh: exec format error
------
failed to solve: process "/bin/sh -c apk update &&   apk upgrade &&   apk add git" did not complete successfully: exit code: 1
```

Any thoughts would be greatly appreciated.

Also, I would like to provide some feedback around the setup process so far:
1. I would have loved to see the necessary containers published on a registry and made available from get go.
2. To add to the above, provide a docker compose file (as documentation example) that can spin up a working instance, without 
 needing to clone the repository. This will also make docker updates monitoring much easier as the registry can be checked for updates instead of the github repo. `docker compose down && docker compose pull && docker compose up -d` instead of https://docs.bigcapital.ly/deployment/docker#upgrading
3. Going hand in hand with the above, i personally would not need an nginx container. Instead I am using nginx proxy manager and handling the serving myself. Again, this means making changes to the docker compose file and not being in sync with the repo.
4. Quite a few mismatches between `.env.example`, `docker-compose` file and the online documentation. Seems like `DB_HOST` is not used from the env, so seems redundant. No mention in the docs about `AGENDASH_*`, `API_RATE_LIMIT`, `GOTENBERG_*`. Docker compose exposes 3000, nginx 80 and 443, documentation states: `Wait for all containers to be in running state, and then point your browser to http://<IP-ADDRESS>:8000/ to access the application.`
5. On top, the documentation seems to have been written by someone that knows the project for someone that also knows the project. It is documenting "items" but not the context for them. As a software engineer myself I fully understand why this happens. But as I tell my team, write documentation so that anyone, no matter how computer illiterate, can spin up a working copy of your application without even knowing what they did. For example, in your instance, what is system db, what is tenant db, what is their usecase and do I actually need it.

Please do not take this feedback the wrong way. This is not intended as bad mounthing at all, but instead constructive criticism that will hopefully help you better understand your "client" base.

I look forward to your reply and getting a chance to have a play with the application :)
Rob

**Comment by abouolia** [comment]
Thanks for your feedback, I've never tried running the Docker setup on ARM arch. but I added this task in our backlog to run it on ARM CPU on cloud instance and see what the errors we're gonna get.

1. All main containers of the app are published on the cloud registry which is the `server` and `webapp`, the other ones like `migration` container should be built locally it's just container has a tiny layer above the `server` container.
2. Yup, one of the plans we have, we're wanna split up the docker configure out of the main repo in a separate repo to make the cloning faster but recently we've been busy doing other stuff. but we'd love to take external contribution from external contributors in that. (btw in all cases updating containers should be done by pulling out the latest version of images from registry and git pull has nothing to do with upgrading just just if there was updates in docker-compose config in the new update).
3. You can use nginx manager easily without any problem and btw I've used it once to one of our customers, the point of nginx that has been used, is used as gateway connects between the server and webapp since the app is SPA, but out of it you can use any proxy you want. (if you have other options please let us know, btw in the future once we migrate to next.js we will get rid of that gateway)
4. Thanks to let us know, some env vars have been added recently we didn't add them in docs. 
5. In the meantime the only setup method is by Docker, we will document the raw way and let the user configure the app in any way they want, the note is taken. but in terms of your questions what is system db etc. https://docs.bigcapital.ly/architecture documented here the whole architecture of the app take a look at it.

Not at all I didn't take it as criticism at all, a lot of points are taken, we will improve it gradually but recently as I said we have been really busy to iterate around the software to ship more new releases, let me know if you have other questions, notes or feedback.

**Comment by robertalexa** [comment]
Hey @abouolia 

Thanks for the response. I appreciate you finding the time to write back.

To avoid the current blocker with the `migration` container, from what i can deduct from the code this seems to be needed just once for the purpose of running database migrations?

If my assumption is correct, am i right in thinking that I could start without this container, and exec `node ./build/commands.js system:migrate:latest` and `node ./build/commands.js tenants:migrate:latest` straight into the `server` container?

**Comment by kevinzliao** [comment]
I was able to get this working on my Pi 4 8GB after some work. 

-Followed the instructions from https://www.reddit.com/r/docker/comments/td0w9t/comment/i0hjbcs/ (use qemu to emulate around the architectural issue)

```
~/Downloads/bigcapital $ docker exec -it bigcapital-server /bin/sh
/app # ps
PID   USER     TIME  COMMAND
    1 root      4:39 {node} /usr/bin/qemu-x86_64 /usr/local/bin/node node ./packages/server/build/index.js
  143 root      0:00 {sh} /usr/bin/qemu-x86_64 /bin/sh /bin/sh
  169 root      0:00 {sh} /usr/bin/qemu-x86_64 /bin/sh /bin/sh
  176 root      0:00 ps
```

-Use a mongo and nginx image that works with your Pi. In my case I used a Pi 4 so I built an image from  https://github.com/themattman/mongodb-raspberrypi-docker for Mongo 6.0.10 and used that image reference for `docker/mongo/Dockerfile`, but this might not be necessary on the Pi 5. Everything else should work as is.

```
~/Downloads/bigcapital $ git diff
diff --git a/docker/mongo/Dockerfile b/docker/mongo/Dockerfile
index fe60f11..67c674a 100644
--- a/docker/mongo/Dockerfile
+++ b/docker/mongo/Dockerfile
@@ -1 +1 @@
-FROM mongo:5.0
\ No newline at end of file
+FROM pi-mongo:6.0.10
diff --git a/docker/nginx/Dockerfile b/docker/nginx/Dockerfile
index c48d3a8..0e31fe0 100644
--- a/docker/nginx/Dockerfile
+++ b/docker/nginx/Dockerfile
@@ -1,4 +1,4 @@
-FROM nginx:1.11
+FROM nginx:1.25.4
```

Hopefully this helps. Also hopefully we can get official support for ARM but this should work for now...

**Comment by cloudsbird** [comment]
It's merged so we can close this issues @abouolia
