### ISSUE TITLE
Customer emails addresses gets the "." removed when a new one is added

### ISSUE THREAD

**Issue by gitmp01** [bigcapitalhq/bigcapital#306]
When creating an new customer, if I put an email like
```
example.customer@provider.com
```

becomes

```
Examplecostumer@Provider.Com
```

Not great :)

**Comment by asenawritescode** [comment]
@abouolia 

I have replicated the issue but I can see that it is capitalizing but the "." is retained.
See screenshots below.

![image](https://github.com/bigcapitalhq/bigcapital/assets/67445192/a5ba91bf-8973-427b-af3e-3f1310f6a88c)

@gitmp01 Please specify the exact page so that I can look into it.

**Comment by gitmp01** [comment]
Path to reproduce is
Contacts -> New Customer -> Set required field and email `hello.world@gmail.com` -> Save

Resulting email when displaying the customer is `Helloworld@Gmail.Com`

I'm on tag `v0.13.1`

**Comment by asenawritescode** [comment]
@abouolia 

I have been able to replicate this, it is selective. I wonder why.
![image](https://github.com/bigcapitalhq/bigcapital/assets/67445192/1a634beb-57c2-496b-8ecb-794ea41542dc)
![image](https://github.com/bigcapitalhq/bigcapital/assets/67445192/15b97845-cdec-4a8b-a4a2-000414bf0bad)

**Comment by asenawritescode** [comment]
It could be hitting the backend too. 

Response from the api does not have the full-stop in "hello.world"
![image](https://github.com/bigcapitalhq/bigcapital/assets/67445192/f7441a4a-1ce6-4db9-9be6-6e104031ef97)
