### ISSUE TITLE
Show the manual journal date on the drawer.

### ISSUE THREAD

**Issue by abouolia** [bigcapitalhq/bigcapital#583]

**Comment by LaszloDev** [comment]
Can you provide some context, maybe page/url/screenshot of where the “drawer” is and in what format the “date” should be shown, and where the date is coming from?

**Comment by abouolia** [comment]
The drawer is slider that shows all the expense details just search about expense drawer in the code base you'll find it, actually the api retrieves the [formatted date](https://github.com/bigcapitalhq/bigcapital/blob/develop/packages/server/src/services/Expenses/CRUD/ExpenseTransformer.ts#L62) value just we want to add it on the drawer in appropriate place.

**Comment by Champetaman** [comment]
Hi @abouolia,

I was reviewing the implementation related to this issue and noticed that the formatted date is already being retrieved and placed in the `ExpenseDrawerHeader.tsx` using the `ExpenseDrawerProvider.tsx`.

``` Typescript
<DetailItem label={<T id={'published_at'} />}>
      {expense.formatted_date}
</DetailItem>
``` 

Here's where I found the manual journal date:
![image](https://github.com/user-attachments/assets/8cc25f59-f186-4c37-9575-3d8870a175e4)


Given this setup, it seems like the requirement to display the manual journal date in the drawer is already fulfilled. Could you please confirm if this issue is still open, or if there are any additional adjustments needed?

Thanks!

**Comment by abouolia** [comment]
Oh, got it, labeled under Published at, it should be “Date”, label, there’s an another attribute called created_at should be for Published At label if you didn’t find the formatted copy of created_at, add it from the backend through ManualJournalTransformer class (if still remember the name correct)

Add Date then Published At in that order.

**Comment by Champetaman** [comment]
Just opened the Pull Request #612 in order to fix this bug.
